name: cicd sandbox thomas 

on:
  push:
    branches:
      - 'sandbox/thomas/**'

jobs:

  build:
    uses: ./.github/workflows/build.yml
    permissions:
      id-token: write
      contents: read
    secrets: inherit

  deploy:
    needs: build
    uses: qbit42-ai/aws-management/.github/workflows/_deploy.yml@main
    permissions:
      id-token: write
      contents: read
    secrets: inherit
    with:
      ENVIRONMENT: sandbox-thomas
      AWS_REGION: eu-central-1
      STACKNAME: RagApiStack
