name: Docker Dev Images Release

on:
  release:
    types: [published]

jobs:

  build:
    uses: qbit42-ai/aws-management/.github/workflows/_build.yml@main
    permissions:
      id-token: write
      contents: read
    secrets: inherit
    with:
      ENVIRONMENT: shared-services
      AWS_REGION: eu-central-1
      REPO: qbit42-rag-api
      RELEASE: ${{ github.ref_name }}
